### ISSUE TITLE
[TASK] Complete UI Builder 'Modal' block

### ISSUE THREAD

**Issue by iclyn-taero** [SEMOSS/semoss-ui#146]
### Description 

I would like to be able to have a modal in my drag and drop apps, where i can add blocks within them as well.

### Existing

Currently there is a started Modal Block that lives in block-defaults.  What's needed is to be able to drag and drop blocks within it while it is open.  We have the open property set to true so we can test out the drag and drop functionality which does work.  We will have to expand the components within client/src/components/designer to be able to account for the ghostPosition while hovering within a modal.

**_Components to look at_**
ModalBlock.tsx
Screen.tsx
Ghost.tsx
HoveredMask.tsx
Placeholder.tsx

### Tasks
- [ ] Ensure i can drag and drop a modal into my block tree, this will be a child of our page block
- [ ] Allow children blocks to be dropped within our new modal block,  visual indicators for dragging are shown within the modal
- [ ] The data config for said block is editable on the right hand side panel (open is the only property i envision)
- [ ] Think through conditional rendering of the modal (just think through this)

**Comment by anurag91jain** [comment]
This has been merged. @neelneelneel @johbaxter could we close this issues?
