### ISSUE TITLE
[TASK] Workflow Tool Documentation

### ISSUE THREAD

**Issue by iclyn-taero** [SEMOSS/semoss-ui#217]
### Description 

Document what existing classes / reactors exist in the Ai4RR code base, as well as the MDE code base, to help create a generalized workflow tool. 

The Work Flow tool should be extendible and be able to be used besides the VA workflow. 

### Existing

MDE and Ai4RR code base can be good to re-use for workflow tool. 

### Reference

N/A

### Tasks

- [x] What should a workflow table(s) schema look like?
- [x] How do you move a workflow item from one stage to another?
- [x] How do you assign a workflow item from one recipient to another?
- [x] How do you ensure only one person can work on a case at a particular time?
- [x] What base classes / reactors in MDE can be re-used?
