### ISSUE TITLE
[TASK] Prototype UI for AI Conductor

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss-ui#219]
### Description 

Add a new route for our AI conductor, and start the mapping of tasks that get generated for the prompt a user asks.  This list of tasks will come from the Backend.  But for the time being we will hardcode a list of tasks that represent a list of our drag and drop apps.

For MVP we will need to map out this list of tasks, and for each task show the inputs that are tied to that particular app/task.  These inputs will then be gathered from our user (require them to be filled out), to then be consumed as an api for that specific app/task.

_**Things to keep in mind:**_
This list of tasks may not always have an associated app for them, we have to keep this in mind and allow the user to create the app associated to said task.

### Existing

N/A

### Reference

This issue references https://github.com/SEMOSS/community/issues/2

### Tasks

- [x] SEMOSS/semoss-ui#221
- [ ] Take prompt, and return an array of tasks that accomplish prompt, with list of app id's tied to task
- [ ] SEMOSS/ai-conductor#65
- [x] SEMOSS/semoss-ui#240
- [ ] Execution of tasks and outputs per app (AI Conductor)
- [ ] Scaffold UI and Set up chat Interface (AI Conductor)

**Comment by johbaxter** [comment]
Update:
Phillip Kem started a prototype to get the thought process going.

Neel also started a branch called 'ai-pipeline' that utilizes react flow and some idea on the DS that we will have for the pipeline.  Should have some stuff about isInput and isOutput.  But likely alot more to handle different types of operations.

![Image](https://github.com/user-attachments/assets/b3a57daf-109f-44b0-a38e-f3acdfe9ac19)

@tombetthauser will get you to look at branch and get exposure, will ask you to take lead on this.  Will be along side as well.

**Comment by tombetthauser** [comment]
started new branch [219-prototype-ai-conductor](https://github.com/SEMOSS/semoss-ui/tree/219-prototype-ai-conductor)

**Comment by natdink** [comment]
Update from convo with PK and George 9/24:

This is after an initial chat has been asked...
1.  A Subtask is queued and user is given a list of apps as options to select from
2. User selects an app (also can return to app options and could reselect an alternate app)
3. App shows as you would see in ui builder
4. User also specifically sees the inputs and outputs of the app
5. User must map the app inputs and outputs to the subtask inputs and ouputs AND so will need to see the structure/type of each of the input/outputs as well as potentially have a 'convert to json' button (ex: if app expects a file input for app input "a" but the subtask expects an integer for subtask input "A", user will need button to convert app input to expected data type)
6. if a type is not supported, user could 'hardcode' the input to whatever they want 
7. they click run to run subtask and continue

**Comment by natdink** [comment]
- updated app cards last week and incorporated PK's ask to include the app cards as mini versions in the second step so user has flexibility to move between apps without having to go back another screen
- note: does not want to incorporate more chat features

- [ ] new ask: look at app card sizing and refactor
- [ ] new ask: update input output mapping to be more visual-based
