### ISSUE TITLE
[TASK] Name validation on App Creation 

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss-ui#224]
### Description 

We need to add in a few validations for App Name creation, on our workflows that allow us to create an app.

### Existing

All of our App creation workflows live on this route `http://localhost:9090/semoss-ui/packages/client/dist/#/app/new`

### Reference

This issue references https://github.com/SEMOSS/community/issues/13

![image](https://github.com/user-attachments/assets/7c3b0af5-fce5-4d9b-9394-d36411deb5fc)

### Tasks

- [ ] Ensure App Name is not a duplicate - `CheckProjectName("user input name");`
- [ ] Ensure special chars are not allowed in the name
- [ ] Ensure the App does not start with a number (must start with number)
- [ ] Ensure that the validation is in place for (Agent Builder, Code Apps, Drag and Drop Apps, All Template Apps, and Upload via an Assets copy)

**Comment by johbaxter** [comment]
This has been tasked off to Anurag on the USI team.  He will link PR to ticket upon completion.
