### ISSUE TITLE
[TASK] Prototype a CreateItem Reactor

### ISSUE THREAD

**Issue by iclyn-taero** [SEMOSS/semoss-ui#235]
### Description 

Creating a Item Reactor that should query a database for it's values and return the object so the information can be updated or modified. 

### Existing

Will be looking at code from the MDEO repo to see how they assign or modify case information. 

### Reference

This issue references #217 

### Tasks

- [ ] Item Reactor should create an object with the same attributes as the database to test locally.
- [ ] Make sure Dates are correctly added 
- [ ] Ensure Attributes are not Null
