### ISSUE TITLE
[TASK] Refactor state logic and prepare for future features

### ISSUE THREAD

**Issue by neelneelneel** [SEMOSS/semoss-ui#240]
### Description 

Refactor state logic

### Existing

n/a

### Reference

`state.store.ts`, `MigrationManager.ts`

### Tasks

- [ ] Rename instances of queries to notebook
- [x] merge dependencies into variables as a `value` property on each variable 
- [x] add `input` Boolean to each variable for API execution
- [x] add `output` Boolean to each variable for API execution
- [x] Fix logic for variable add and edit for once called dependencies
- [x] Get rid of dependency value evaluation in state store
- [x] add UI for input and output on variables
- [x] add UI to set sheet execution order
- [x] add a property that saves the order of notebooks for API Execution
- [x] Update the version and add migration functions to `MigrationManager` to convert old notebooks into the new version

**Comment by neelneelneel** [comment]
Related to #219
