### ISSUE TITLE
[TASK] Allow filters on the catalog pages to be url addressable

### ISSUE THREAD

**Issue by neelneelneel** [SEMOSS/semoss-ui#246]
### Description 

Allow filters to be url addressable (as url parameters)

![image](https://github.com/user-attachments/assets/f974914c-a574-4319-8a10-5cca45b4abe1)

### Existing

`EngineCatalogPage.tsx`
`HomePage.tsx`

### Reference

This issue references. . .

### Tasks

- [ ] Allow for single and multiple selection of filters
- [ ] Fix engine catalog on `EngineCatalogPage.tsx`
- [ ] Fix home page on `HomePage.tsx`
