### ISSUE TITLE
[TASK] Bar Chart - Axis 

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#364]
### Description 

Create component for axis that can be used in multiple charts such as bar and line charts within AI Core 

### Tasks

Necessary features include: 
- [x] Show/hide each axis
- [x] Add axis titles, show/hide axis titles
- [x] Edit label font size
- [x] Show tick marks 
- [x] Rotate axis values (by a degree amount)

**Comment by bannaarisamy-shanmugham-kanini** [comment]
Working on adding proper comments for the component files.
