### ISSUE TITLE
[TASK] Bar Chart - Styling

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#366]
### Description 

Create styling tools to be used within bar chart 

### Tasks
- [x] Change bar colors 
- [x] Color by value
- [x] Set font size and color 
- [x] Edit bar width

**Comment by bannaarisamy-shanmugham-kanini** [comment]
working on adding proper comments to the components.

**Comment by bannaarisamy-shanmugham-kanini** [comment]
@ehynd , The font size and colour is fixed.
