### ISSUE TITLE
Bar chart - features 

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#367]
### Description 

Features for bar chart in both Vega and Echart

### Tasks
Tools include:
- [x] Legend - toggle on/off
- [x] Customize value labels
- [x] Display value labels 
- [x] Tooltips  - toggle on/off 
- [x] Trendlines - toggles on/off

**Comment by bannaarisamy-shanmugham-kanini** [comment]
Following items are completed and tested in local:
Legend - Toggle On/Off
Customize Value Labels
Display Value Labels
Tooltips - Toggle on/Off

Need to verify:
Trendlines - Toggle on/off

**Comment by bannaarisamy-shanmugham-kanini** [comment]
Trendlines - Toggle on/off - working
