### ISSUE TITLE
[TASK] Pie chart - styling

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#369]
### Description 

Styling tools for pie chart 

### Tasks

Must include following tools: 
- [x] Change color
- [ ] Color by value
- [x] Set font size and color
- [x] Donut - toggle to/from donut chart

**Comment by JaganSomannaKanini** [comment]
In the color by value, one scenario (is equal to) is completed.
Remaining scenario is in progress.

**Comment by JaganSomannaKanini** [comment]
Color By Value: 

1. All scenario's (is equal to, is not equal to, is lesser than, is lesser than or equal to, is greater than, is greater than, is greater than equal to) is 95% complete. I am working on small issues related to this part and code optimization as well. 
2. The "Rule's applied" section where all the rules which are applied is displayed above is remaining.
