### ISSUE TITLE
Pie chart - features

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#370]
### Description 

Features tools for pie chart in both Vega and Echart 

### Tasks
Must include the following tools: 

- [ ] Legend
- [x] Customize value labels
- [x] Display value labels 
- [x] Tooltips  - toggle on/off
