### ISSUE TITLE
[TASK] Create Top Navigation Bar Grouped Component

### ISSUE THREAD

**Issue by rithvik-doshi** [SEMOSS/semoss-ui#378]
### Description 

Create a component that, when dropped, adds a grouped component top navigation bar to the website. The navigation bar should consist of navigation buttons that are linked to navigate to other pages in the website. If multiple pages do exist, they should be automatically linked and the button text should reflect that; else, create a template navigation bar with template buttons with no action.

### Existing/Reference

#375 will introduce grouped components.

### Tasks

- [ ] Create a grouped component based on #375 
- [ ] Add navigation button components #390 to this group component
- [ ] Add an action to each button to navigate to the page that is specified by the button
- [ ] Add this grouped component to the grouped component section in the UI
