### ISSUE TITLE
[TASK] Create a Confirmation Dialog grouped component

### ISSUE THREAD

**Issue by tevanburen** [SEMOSS/semoss-ui#381]
### Description 

Create a grouped component that, when dropped, displays a button that when clicked opens a dialog with text and two buttons. An example use case would be a submit button linked to an "Are you sure you want to submit?" Dialog. Another example use case would look similar to:
![image](https://github.com/user-attachments/assets/f55f69ea-a4ca-4c2d-b17f-df6d572a3200)

### Existing / Reference

#375 will introduce the first grouped component

### Tasks

- [ ] Create a Dialog component
- [ ] Create a Grouped Component consisting of the Dialog, title text, and subtitle text similar to the example image
- [ ] Include three buttons in the Grouped Component - one that lives on the page that opens the Dialog, and two that live on the Dialog (think "back" vs "forward" buttons) that close the Dialog

**Comment by neelneelneel** [comment]
Dependent on #357
