### ISSUE TITLE
[TASK] Expand Table Functionality

### ISSUE THREAD

**Issue by neelneelneel** [SEMOSS/semoss-ui#385]
### Existing
-  [TableBlock.tsx](https://github.com/SEMOSS/semoss-ui/blob/dev/packages/client/src/components/block-defaults/table-block/TableBlock.tsx)

### Tasks
Expand functionality to include:
- [x] When bound to a frame, pull data automatically onPageLoad (or changes)
- [x] When bound to a frame, add a context menu to filter and unfilter
- [x] Expose right menu

**Comment by neelneelneel** [comment]
Renamed to GridBlock.tsx
