### ISSUE TITLE
[TASK] Update File Explorer to use shadcn

### ISSUE THREAD

**Issue by neelneelneel** [SEMOSS/semoss-ui#393]
### Description 

Update File explorer to use shadcn

### Existing

[src\components\common\file](https://github.com/SEMOSS/semoss-ui/tree/dev/packages/client/src/components/common/File) contains relevant file components

### Tasks

- [ ] Add ability to view files at a path
- [ ] Add ability to delete files
- [ ] Add ability to create a new file
- [ ] Add ability to add a new file

**Comment by ehynd** [comment]
Blocker: BE updates required

**Comment by ehynd** [comment]
fe ticket
