### ISSUE TITLE
Create Scatter Plot 

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#398]
### Description 

Create scatter plot chart block within new UI 

### Tasks

The following data fields, tools, and styling must be included within the chart. 

Fields
- [x] x-axis
- [x] y-axis 
- [x] Label
- [x] Size (of each mark)
- [x] Color (of each mark) 
- [x] Tooltip 

Events
- [x] Brush event 
- [x] Click event

Axis Features
- [x] Show/hide each axis
- [x] Add axis titles
- [x] Show/hide axis titles
- [x] Edit label font size of axis titles 
- [x] Show tick marks 
- [x] Rotate axis values (by a degree amount) 

Styling 
- [x] Change color scheme
- [x] Set font size and color of values
- [x] Customize symbol shape and size (increase/decrease size, change to open circle/square/star/triangle marker)

Features
- [x] Display value labels
- [x] Customize value labels (choose position for the value label, rotate label by a certain degrees, select font and font size and font color)
- [x] Toggle tooltips on/off 
- [x] Ability to resize chart
- [x] Chart title

**Comment by NaveenRamasamy028** [comment]
@ehynd Toggle Trendlines are not available in legacy for Scatter Plot.

**Comment by ehynd** [comment]
@NaveenRamasamy028 its called a regression line in legacy but function the same as a trendline - is that possible in new code?

**Comment by ehynd** [comment]
This is looking great!! 

Few bugs I'm seeing, mostly around data field selections:

Tooltip not showing up
- Selecting a field for tooltip makes the chart go blank
- even when tooltip is toggled on, no values show up when hovering over a dot 

Color:
- selected field for color, dots stayed black 

Size
-selected field for size, dots did not change size

**Comment by NaveenRamasamy028** [comment]
@ehynd  looking into it

**Comment by ehynd** [comment]
@NaveenRamasamy028 this is looking pretty good! a few comments: 

Priority 1: can you take one more look at the data field selection? 

For reference these are the steps I'm following to look: 
In the data notebook, I pulled in the diabetes data frame using this in pixel (I believe you already have this in there) 
Database ( database = [ "a63cd720-590e-4518-987c-c0693bdf3198" ] ) | Select ( DIABETES__DIABETES_UNIQUE_ROW_ID , DIABETES__Drug , DIABETES__age , DIABETES__bp_1d , DIABETES__bp_1s , DIABETES__bp_2d , DIABETES__bp_2s , DIABETES__chol , DIABETES__frame , DIABETES__gender , DIABETES__glyhb , DIABETES__hdl , DIABETES__height , DIABETES__hip , DIABETES__id , DIABETES__location , DIABETES__ratio , DIABETES__stab_glu , DIABETES__time_ppn , DIABETES__waist , DIABETES__weight ).as ( [ DIABETES_UNIQUE_ROW_ID , Drug , age , bp_1d , bp_1s , bp_2d , bp_2s , chol , frame , gender , glyhb , hdl , height , hip , id , location , ratio , stab_glu , time_ppn , waist , weight ] ) | Distinct ( false ) | Limit ( 20 ) | Import ( frame = [ CreateFrame ( frameType = [ "PY" ] , override = [ true ] ) .as ( [ "FRAME_47606" ] ) ] ) ; Frame ( frame = [ "FRAME_47606" ] ) | QueryAll ( ) | Limit ( 20 ) | CollectAll ( ) ;

Then, for data fields I selected:
label: age
x-axis: height
y-axis: weight

I tried setting gender for color and it didn't work. Similarly, when I removed field, the chart should return back to its original state as if it it was never selected in the first place.  That should go for any of the fields. 

Could you please take another look and compare it to the behavior in legacy? 

Priority 2: Ability to resize, please check in with Banari and Jagan on implementation so all charts have the same approach. 
Priority 3: Continue implementing the UI designs from the Figma, making sure all tools are transferred over

Thank you!

**Comment by NaveenRamasamy028** [comment]
@ehynd i will take a look into it

**Comment by ehynd** [comment]
A few fixes please! 

 - [x] When I drag the block settings panel larger, the content within should resize too. 
<img width="592" alt="Image" src="https://github.com/user-attachments/assets/4da3c188-50da-476c-ba5c-3cd5ee4cae7a" />

- [x] Change spelling to "triangle" in symbol shape 
<img width="150" alt="Image" src="https://github.com/user-attachments/assets/e89caebe-b88c-4068-b7c7-03cc1a0fce60" />

- [x] Sizing still not quite there.  It looks like the sizing is happening at the wrong point. In this example, I have an outer red container that I dragged the chart into.  Then, I set the chart's width at 50%. What's happening is that the chart container is going to 50% of the red container, but then the chart itself is going to 50% of its container.  

This is coming from the const StyledNoDataContainer inside ScatterPlot.tsx inheriting the height and width from StyledNoDataContainer inside of EchartVisualizationBlock.tsx.  Could you please take another look at this? The ScatterPlot size should likely be at 100% and then only the EchartVisualizationBlock container will change size, and the plot itself will update with it.  

![Image](https://github.com/user-attachments/assets/f303c1a1-5107-4815-966d-a2da435a5527)

**Comment by NaveenRamasamy028** [comment]
@ehynd will take a look into this

**Comment by ehynd** [comment]
@NaveenRamasamy028 could you please look at resizing height when using percent? the red container is set at 800px x 800px. the height and width of chart are set at 100%, but the actual height is only at 350px. i think its coming from lines 59-63 of EchartVisualizationBlock.tsx 

<img width="1472" alt="Image" src="https://github.com/user-attachments/assets/2a7a4e9e-0ecc-4f17-b64c-fbc31e149428" />

**Comment by NaveenRamasamy028** [comment]
@ehynd looking into it

**Comment by ehynd** [comment]
sizing looks good!!

**Comment by NaveenRamasamy028** [comment]
Working on Design Issues and color palatte

**Comment by NaveenRamasamy028** [comment]
@ehynd  Working on Scenario Which we Have Discussed 
Scenario : Whenever we are selecting color either by color Palatte or through DropDown Field in Data Part. Whichever the color we last applied should apply to the chart
