### ISSUE TITLE
Create Line Chart

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#399]
### Description 

Create Line Chart Block in new UI 

### Tasks

The following data fields, tools, and styling must be included within the chart. 

Fields
- [x] x-axis
- [x] y-axis 
- [x] Tooltip 
- [x] Ability to add/select multiple y-fields for a multi-line chart. Ex: I select age for x but can select bp1d AND bp1s for y

Events
- [ ] Brush event 
- [x] Click event

Axis Features
- [x] Show/hide each axis
- [x] Add axis titles
- [x] Show/hide axis titles
- [x] Edit label font size of axis titles 
- [x] Show tick marks for x-axis
- [x] Show tick marks for y-axis
- [x] Rotate axis values (by a degree amount) 

Styling 
- [x] Change color scheme
- [x] Add chart title
- [x] Curve type (how the line is formed) options of smooth, exact, step 
- [x] Choose line type (solid, dashed, dotted)
- [x] Choose line weight 

Features
- [x] Legend - toggle on/off
- [x] Display value labels
- [x] Customize value labels (choose position for the value label, rotate label by a certain degrees, select font and font size and font color)
- [x] Toggle tooltips on/off 
- [x] Ability to resize chart

**Comment by Paulson-Robert** [comment]
Branch : **[feat/Echart_LineChart](https://github.com/SEMOSS/semoss-ui/tree/feat/Echart_LineChart)**

**Comment by ehynd** [comment]
Added new field task - need to be able to multi-select/add on the y-fields so there can be multiple lines within the same chart

**Comment by ehynd** [comment]
@JaganSomannaKanini this is looking great functionality wise! 
After pie chart, please continue working through a few things on it: 
Priority 1: Seeing the same issue as pie when I save and reopen 
Priority 2: Make sure sizing is following the same approach as bar and pie 
Priority 3: Continue adding in the Figma designs, making sure all tools are accounted for as you move them over.

**Comment by JaganSomannaKanini** [comment]
As the Pie chart is completed, I have started working on the styling part of the Line chart.

**Comment by JaganSomannaKanini** [comment]
Completed the Title, X Axis styling and toggles such as Tooltip and Legend.

**Comment by JaganSomannaKanini** [comment]
New Updated branch : [https://github.com/SEMOSS/semoss-ui/tree/399-echart-line-chart](399-echart-line-chart)

I have linked the new branch name into this ticket (Linked in the development tab)

**Comment by JaganSomannaKanini** [comment]
Hi @ehynd , created the pull request for Line chart. Plese take a look.
https://github.com/SEMOSS/semoss-ui/pull/688
