### ISSUE TITLE
Create Map Chart

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#400]
### Description 

Create map chart block in new UI 

### Tasks

The following data fields, tools, and styling must be included within the chart. 

Fields
- [x] Label
- [x] Latitude 
- [x] Longitude
- [x] Size (category/column that determines size of each point on the map) 
- [x] Color (category/column that determines color of each point on the map) 
- [x] Tooltip 

Events
- [x] Brush event 
- [x] Click event

Styling 
- [x] Map marker size - changes the default marker size for data points (default in legacy is 5) 

Features
- [x] Legend - toggle on/off
- [x] Toggle tooltips on/off 
- [x] Resize chart 
- [x] Color Pallette
- [x] Color Picker

**Comment by bannaarisamy-shanmugham-kanini** [comment]
@ehynd , I have worked on resizing of Map chart and committed my changes to EChart-Map-Chart-Dev branch.
Kindly suggest me if any further changes required.

**Comment by ehynd** [comment]
@Gowrishankar-Palanisamy could you please pick up on this where Banari left off?

**Comment by Gowrishankar-Palanisamy** [comment]
Yes , I will take over from where Banari left off and continue working on this

**Comment by ehynd** [comment]
@Gowrishankar-Palanisamy  a few things! I emailed you the dummy database I was using. 

- [x] could you please take a look at the latitude and longitude? I think they're switched.  Ex: when I put them into the data fields as is, I get all my dots in the ocean in the middle of the map.

<img width="1499" alt="Image" src="https://github.com/user-attachments/assets/681bc350-de8f-49fc-a063-3b716cb831e3" />

If I switch them and put the long data into lat and the lat data into long, it populates correctly

<img width="1484" alt="Image" src="https://github.com/user-attachments/assets/ea4a2109-a595-4faa-9a1a-b22ecc524633" />

- [x] Sizing within the map as a whole. Could you play around with changing the default size? The dots are quite difficult to see, and while the user can go in and change the marker size themselves, it would ideally default to something slightly more visible.  Maybe reference the legacy system map sizing?

<img width="1826" alt="Image" src="https://github.com/user-attachments/assets/b408a161-1ea7-4466-82f0-48aa0ff375ed" />

- [x] Similarly to the default sizing, the sizing data field could be improved.  In this example, I selected "Importance" in the sizing field, but it is quite difficult to see any size difference:


<img width="1400" alt="Image" src="https://github.com/user-attachments/assets/04cc3023-a430-4199-97cb-7f79e2a39325" />

This is what the same options look like in legacy:

<img width="1796" alt="Image" src="https://github.com/user-attachments/assets/abb576ec-e2d7-4f6d-b4ee-e7d8256fc7cb" />


- [x] Naming: In the left side menu, could you please change "Map Chart" to "World Map Chart"?  

<img width="236" alt="Image" src="https://github.com/user-attachments/assets/635601f4-c4b1-4568-9f60-55b837c79df9" />

In the right side menu, could you please change "Echart Map Graph" to "Echart World Map Chart"? This will just keep the naming consistent.  

<img width="493" alt="Image" src="https://github.com/user-attachments/assets/ef200379-73be-4207-aab7-83022212c710" />

**Comment by Gowrishankar-Palanisamy** [comment]
I'm looking into it
