### ISSUE TITLE
[TASK] Create KPI Block

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#401]
### Description 

Create KPI block to be used in new UI 

### Tasks

The following data fields, tools, and styling must be included within the chart. 

Fields
- [ ] Dimension (should be able to include multiple columns/categories) 

Styling 
- [ ] Font color on card
- [ ] Background color of card
- [ ] Font 
- [ ] Set font size for value (main number)
- [ ] Set font size for title (below number)
- [ ] Select alignment within card (right, center, left)
- [ ] If two KPIs in one block (ie include multiple columns in dimension), should be able to select which column to apply settings to, or apply to all

**Comment by neelneelneel** [comment]
The text block should be able to handle this. The user can duplicate to use multiple values
