### ISSUE TITLE
[TASK] Update Grid Block

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#402]
### Description 

Increase functionality of existing grid block in new UI.  Would suggest starting with seeing how the grid functions in legacy, we want to replicate some of that and change some of that 

### Existing

Current grid ability within new UI: 
- [ ] Select frame and columns
- [ ] Toggle pagination on/off

### Tasks

The following updates should be added to the grid functionality around styling and events: 

Events
- [x] Click event 

Styling 
- [x] Header background color
- [x] Header font color/size 
- [x] Cell font color/size 
- [x] Color by value (should apply to one cell with ability to checkbox to apply to entire row if desired)
- [x] Add title (Chart title, font size, font color)

Features
- [x] Toggle row spanning
- [x] Wrap text within cells 
- [x] Resize columns (in legacy UI, the user is able to drag the column to resize within the panel. Does not need to be accomplished in the exact same way) 
- [x] Resize chart

**Comment by ehynd** [comment]
there is a completed design in figma for this grid block: https://www.figma.com/design/Qj4tWPsniFOJ6qSLfxOaBT/UI-Builder---Design?node-id=11455-103145&t=FvRxuEjeFS0ADRr9-0

**Comment by Shubham009-prog** [comment]
Hi, I was having some clarifications:

1. How will Resize column will work as I have checked currently there in drag column option in MUI Grid ?
2. In Toggle Row Spamming there is only one switch button. How will row spanning Work?
3. What will be in the applied rule in color by value (currently not mentioned anything in UI)?

**Comment by Shubham009-prog** [comment]
Hi, As per our discussion yesterday, I will proceed with integrating a data grid in place of the standard table. This change will involve significant modifications to the functionalities I have already implemented. 

Additionally, I need to explore column resizing on drag functionality, which may require further adjustments. Considering these updates, I anticipate that the task will take more time to complete.

**Comment by ehynd** [comment]
All sounds good! Pushing out the timeline makes complete sense given the change in direction. 

Just for tracking this is our plan on this one:
- duplicate existing table 
- create new component for MUI data grid 
- begin implementation of tools / updates in the MUI data grid, leaving existing table component as is

**Comment by Shubham009-prog** [comment]
Hi, I have successfully Integrated DataGrid along with pagination and resizing column using drag. Also have reimplemented some of features like header and cell styling along with text wrapping, Its also working fine with new data Grid. Also attached screenshot of the progress below:

![Image](https://github.com/user-attachments/assets/0647af44-d88a-451a-9856-881d7f3f1bd6)

**Comment by Shubham009-prog** [comment]
Hi @ehynd , I have implemented the color by value feature. 

![Image](https://github.com/user-attachments/assets/ca8b314e-93b5-4e1f-82ea-91772f99e5c6)

After discussion with sayali, she is saying that this design is not approved yet could you confirm about it?

**Comment by ehynd** [comment]
Hi @Shubham009-prog that's essentially it! Just left one more comment in the figma and then we should be good to go. it looks great!

**Comment by Shubham009-prog** [comment]
Hi, I am currently working on the click event. As discussed yesterday I am doing it in same was as its working on the other charts.

**Comment by Shubham009-prog** [comment]
Hi, I have raised the PR. Please have a look  [https://github.com/SEMOSS/semoss-ui/pull/966](url)

**Comment by ehynd** [comment]
@Shubham009-prog when you get back, could you please update this branch? pull in dev and resolve any conflicts, want to get it merged next week

**Comment by ehynd** [comment]
@Shubham009-prog this one instead please! pull in dev and resolve any conflicts, there's a few things I know have changed in the last month to be integrated here
