### ISSUE TITLE
[TASK] Theme Block

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss-ui#407]
### Description 

Create a new block that utilizes the Material UI theme

This should be a block that is added to the JSON by default similarly to how the page block is set.  This will wrap all children blocks that are on the current page

The 

### Existing

[block-defaults](https://github.com/SEMOSS/semoss-ui/tree/dev/packages/client/src/components/block-defaults)
[Material theme documentation](https://mui.com/material-ui/customization/default-theme/)

### Reference

N/A

### Tasks

What are more specific tasks that a developer needs to take to consider this issue resolved.

- [ ] Create Block that utilizes material theme wraps all children blocks
- [ ] Create custom settings to toggle between modifying Material JSON via JSON editor and user friendly inputs (both must update JSON in unison)
- [ ] Create migration function that adds the Theme Block to pre-existing apps.
