### ISSUE TITLE
Create Stack Chart

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#430]
### Description 
Create Stacked Bar Chart in new UI

### Existing
Most of this mimics the bar chart - just need the ability to select category as well to create the stack

### Reference
Legacy chart is called "stacked"

### Tasks

The following data fields, tools, and styling must be included within the chart. 

Fields
- [x] x-axis
- [x] y-axis 
- [x] Category 
- [x] Tooltip

Events
- [x] Brush event 
- [x] Click event

Axis Features
- [x] Show/hide each axis
- [x] Add axis titles
- [x] Show/hide axis titles
- [x] Edit label font size of axis titles 
- [x] Show tick marks 
- [x] Rotate axis labels (by a degree amount) 
- [x] Flip Axis 

Styling 
- [x] Change color palette
- [x] Edit bar width 

Features
- [x] Legend - toggle on/off
- [x] Display value labels
- [x] Customize value labels (choose position for the value label, rotate label by a certain degrees, select font and font size and font color)
- [x] Toggle tooltips on/off 
- [x] Ability to resize chart

**Comment by ehynd** [comment]
@NaveenRamasamy028 SUPER super tiny - can you check the Value Label -> Choose Position tool please? I think inside right and inside left are swapped.  When I select inside right, the labels show up on the inside left, and then vice versa when picking inside left.  After you check that, please raise the PR!

**Comment by NaveenRamasamy028** [comment]
> [@NaveenRamasamy028](https://github.com/NaveenRamasamy028) SUPER super tiny - can you check the Value Label -> Choose Position tool please? I think inside right and inside left are swapped. When I select inside right, the labels show up on the inside left, and then vice versa when picking inside left. After you check that, please raise the PR!

@ehynd as discussed raised the PR
