### ISSUE TITLE
[TASK] Create Area Chart

### ISSUE THREAD

**Issue by ehynd** [SEMOSS/semoss-ui#431]
### Description 

Create Area Chart Block in new UI 

### Existing

A lot of this mimics a line chart - just need to be able to fill in under the curve 

### Reference
Legacy chart is called Area Chart

### Tasks

The following data fields, tools, and styling must be included within the chart. 

Fields
- [ ] x-axis
- [ ] y-axis 
- [ ] Tooltip 

Events
- [ ] Brush event 
- [ ] Click event

Axis Features
- [ ] Show/hide each axis
- [ ] Add axis titles
- [ ] Show/hide axis titles
- [ ] Edit label font size of axis titles 
- [ ] Show tick marks 
- [ ] Rotate axis labels (by a degree amount) 

Styling 
- [ ] Change color under line (the area) 
- [ ] Curve type (how the line is formed) options of smooth, exact, step 
- [ ] Choose line type (solid, dashed, dotted)
- [ ] Choose line weight 

Features
- [ ] Legend - toggle on/off
- [ ] Display value labels 
- [ ] Customize value labels (choose position for the value label, rotate label by a certain degrees, select font and font size and font color)
- [ ] Toggle tooltips on/off 
- [ ] Ability to resize chart
