### ISSUE TITLE
[TASK] Allow Reorder of executed Notebooks tied to all event listeners

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss-ui#432]
### Description 

The event listeners we currently do not allow flexibility of rearranging the notebooks that get executed.  We need to allow draggable behavior to reaarange the notebooks that get executed on event listeners

### Existing

[ListenerSettings.tsx](https://github.com/SEMOSS/semoss-ui/blob/dev/packages/client/src/components/block-settings/ListenerSettings.tsx)

### Reference

[#64](https://github.com/SEMOSS/community/issues/64)

### Tasks

- [x] Allow reorder of executed notebooks on event
- [x] Rename "Run Query" to "Run Notebook" **
- [x] Also show what Notebook is executed right under "Run Query"'

**
![image](https://github.com/user-attachments/assets/19f98683-fea7-46c7-9e2c-2eac13fb6300)
